### ISSUE TITLE
Change config files to .ini instead of binary .cfg file

### ISSUE THREAD

**Issue by Tartifless** [DCurrent/openbor#298] opened 2024-02-23 17:27 UTC
**Is your feature request related to a problem? Please describe.**

I am always frustrated to see the .cfg file in binary format, would be so much easier to work with a readable .ini file.
Also to provide help or support.

**Describe the solution you'd like**

Having a .ini file instead if a binary .cfg file.

**Describe alternatives you've considered**

**Additional context**

**Comment by Darknior** [comment] 2024-02-23 22:04
For sure it is the best way. And there is zero interest to make it not readable ... CFG file dont permit to cheat in games or nothing else ... it is only here to choose some minor options like SCREEN RATIO, or SHADER, etc ...

To enable cheat in games the player must unpack the PAK file ... but for sure, for me this option too should be in the INI file and the user should choose to cheat the game or not.
I can understand the game author is not agree, but it is a player decision ;) And when we are playing with young children it halp a lot, i always add it to all my games ... nut it is not the subject lol

We already do what you want in Batocera from a long time ... we patch the EXE file before compiling it to make a real INI file and let the user configure options in the launcher. for sure it's cool too, to let a user choosing his launcher :)
All our patch are here ...

https://github.com/batocera-linux/batocera.linux/blob/985a9b95b7028886b7be5fb7b264fe5291481eac/package/batocera/emulators/openbor/openbor6412/005-axismanagement.patch

I wish some will be added one day ...

- INI readable file
- The command line launching to use alternate launcher like EmulationStation

The other patch is for us, for our auto gamepad configuration but it is not used out of Batocera.

**Comment by dbaldan** [comment] 2024-02-23 22:22
@Darknior "I can understand the game author is not agree, but it is a player decision ;) '" I strongly disagree.
It's a dev decision, not a player decision. If the dev doesn't want his game to be used with cheats and the player doesn't agree with it, just pick another game to play :)

I really wish we got rid of those infinity health/lives/etc cheats someday.

The good thing is: activating V4 "touch of death" cheat in any game using scripted slams will screw up the enemies.
And that is not a bug: that cheat was supposed to be used by the devs when they develop the game, not bu players.

**Comment by Tartifless** [comment] 2024-02-23 22:32
Why has this deviated in cheats discussion, original request had nothing to do with cheats.

**Comment by dbaldan** [comment] 2024-02-23 22:34
> Why has this deviated in cheats discussion, original request had nothing to do with cheats.

You are right on this one. But there is a ticket that looks like this one already.

**Comment by DCurrent** [comment] 2024-02-23 23:51
Duplicate issue. Closing.

**Closed by DCurrent** 2024-02-23 23:51 UTC

**Comment by Tartifless** [comment] 2024-02-23 23:56
Can you point me to the other issue ? I have checked all opened issue but did not find in the list

**Comment by DCurrent** [comment] 2024-02-24 00:02
It was also closed because of the nature of the request. Config ini for certain options like controllers is already in the works. However, in general, most options will remain in binary config. OpenBOR is not an emulator. It is a game engine, and how those games work is up to the creator.

**Comment by Tartifless** [comment] 2024-02-24 00:04
Only interested in fullscreen, aspect ratio and controllers anyway

**Comment by dbaldan** [comment] 2024-02-24 00:09
> Thanks, good to hear, only interested in fullscreen, aspect ratio and controllers anyway (maybe filters), if these are considered, it would be great.

All those things can be already modified in the game options. No need to add it to an external file .

As Damon said, Open Bor is not an emulator

**Comment by Tartifless** [comment] 2024-02-24 00:23
Controllers is difficult to modify in game options when only a controller is connected.
But that is being worked on, so that's great, fullscreen also might be handy for the same purpose.

Of course it is not an emulator, ans nobody wants it to be, but it runs games through a dedicated executable, so it is also a launcher.

**Comment by dbaldan** [comment] 2024-02-24 00:26
Controllers were fixed in V4 version, you have no problem mapping then anymore.

And no, it's not a launcher either - a launcher executes a second executable. Here you execute the engine itself :)

**Comment by Tartifless** [comment] 2024-02-24 00:30
Please stop this unnecessary discussion.
It's being worked on so it's all fine.

My sentence meant that it is necessary to run openbor.exe, on the opposite of self-contained game executables.

And v4 works fine but when you have no keyboard or mouse, it's impossible to configure a controller, this is why a .ini for controllers is very nice to have.
And knowing we'll have it one day is great !
