### ISSUE TITLE
enemy AI is now affected

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#184] opened 2019-11-13 13:29 UTC
just compiled and tested latest build of PC. I'm unsure if I should report issues or not, there are outstanding issues that haven't been addressed at all (panel, mirror issues etc) and this may seem like simply more work being piled up...

enemy AI has been affected. they now instantly walk away from a player as soon as there is no bbox in a frame of animation and also generally during gameplay walk to and focus on edges of screen, (they also at times get stuck wanting to focus on player or edge of screen and flip excessively)

I am presuming the walk to edge of screen is they are now seeing obstacles as a target (empty.txt) despite no bbox, when I add stealth 350 to bringin and empty this issue seems to be resolved so hope that helps to identify and fix issue.

here is original files info.

here is empty text
`name	Empty
health	10
type	obstacle
shadow	0
offscreenkill	10000

anim idle
	delay	100
	offset	1 1
	frame	data/chars/misc/empty.gif

anim fall
	delay	100
	offset	1 1
	frame	data/chars/misc/empty.gif`

here is bringin text

`name		BringIn
type		panel
speed		10
subject_to_wall	0
subject_to_gravity 0
subject_to_platform 0

anim	idle
@script
  void vSelf = getlocalvar("self"); //Caller.
  void vEntity; //Target entity placeholder.
  int iEntity; //Entity enumeration holder.
  int iType; //Entity type.
  int iName; //Entity name.
  int iMax = openborvariant("count_entities"); //Entity count.
  int iCode; //Entity code.
  int XPos = openborvariant("xpos"); //Get screen edge's position
  int Screen = openborvariant("hResolution"); // Get screen width
  int Ex; int C = 50;

  //Enumerate and loop through entity collection.
  for(iEntity=0; iEntity<iMax; iEntity++){ 
    vEntity = getentity(iEntity); //Get target entity from current loop.
    iType = getentityproperty(vEntity, "type"); //Get target type.
    iName = getentityproperty(vEntity, "defaultname"); //Get target name
    iCode = getentityvar(vEntity, 1);

    //Enemy & NPC type?
    if((iType == openborconstant("TYPE_ENEMY") || iType == openborconstant("TYPE_NPC")) && iCode != 1){
      Ex = getentityproperty(vEntity, "x");

      if(iType == openborconstant("TYPE_ENEMY")){
        C = 50;
      }

      if(Ex <= XPos + C){
        changeentityproperty(vEntity, "position", Ex+2);
      } else if(Ex >= XPos+Screen-C){
        changeentityproperty(vEntity, "position", Ex-2);
      }
   }
 }
@end_script
	loop	1
	delay	1
	offset	1 1
	frame	data/chars/misc/empty.gif
	frame	data/chars/misc/empty.gif`

I use bringin to stop enemies from falling off screen and hanging around offscreen. empty is used for groups etc

**Comment by dbaldan** [comment] 2019-11-13 13:42
@nsw27 Yes, bug reports should be done.

But avoid comments like "I'm unsure if I should report issues or not, there are outstanding issues that haven't been addressed at all (panel issue in particular)". **This doesn't help AT ALL** - on the contrary.

Please stay technical when reporting bugs.
Thanks.

**Comment by nsw27** [comment] 2019-11-13 23:01
sorry but I stand by that comment... and here's why

There are multiple studies that show people are more inclined to report feedback and issues if they know there will be a response.

My suggestions are:

- Establish an overall strategy on how to respond to issues/bugs being reported.
- Create helpful, pre-written responses for general inquiries.
- If a problem will require additional time and support, do not put off responding to the message!  A message stating that you are currently working to resolve the issue, providing a timeline or more information about the problem will be much more appreciated than no response at all.
- Make the effort to be friendly, and show that their feedback is valuable and helps the engine improve and grow.

I've seen too many people leave or just give up... I have faith in the engine and the devs and know things can get better... if you want it to.

**Comment by DCurrent** [comment] 2019-11-24 22:27
Can't reproduce this issue. I test extensively with my own module and more importantly, with the basic template module with every single time I update. After this report I tried removing bboxes and spreading obstacles all over - no difference. It's true the AI isn't particularly good at maneuvering itself around objects, but it never has been, and isn't designed to be by default because sophisticated pathfinding is very expensive and not generally needed. There are several switches and options on the occasion you do need more.
 
I can see right off the bat you have a script that affects positioning and movement. It and any number of other factors could be coming into play. That's what the forum is for. The rest - I've said my peace before and have 0 interest in doing it again. I'm closing this issue.

**Closed by DCurrent** 2019-11-24 22:27 UTC

**Comment by nsw27** [comment] 2020-02-29 12:42
I would like this topic to be reopened. I may be debugging the issue wrong but it is an issue. I can try my best to identify it but its easier to just try and explain what happens and better yet show you all.

here is an example video of the new engine in action. (I compiled this morning so has all the latest updates etc and these videos were taken today right after each other)

This is my version of game without the workaround, band aid fixes to tweak and hide engine changes. such as reverting it so stealth removed for panel and removing offset tweaks to panels to compensate for new engine changes. so you can see the true changes the engine has caused

notice enemies don't attack or notice player outside of ranges, they prefer to focus on other things, they also instantly walk away as soon as player has bbox 0 0 0 0

and the panel offset issues which ive reported on GitHub also in this closed issue https://github.com/DCurrent/openbor/issues/161

also in general is it just me or does it appear to drop frames or something ?


https://www.youtube.com/watch?v=Ogy1o0bRCJU

Now this is a vid showing exact same level on older 'working'' version of Openbor

https://www.youtube.com/watch?v=VW8hEg8oYa4

**Comment by danielt3** [comment] 2020-06-13 21:40
A (great) suggestion (which I used at my work) is that you make a very small PAK file with your exact setup and provide detailed instructions for people to try to reproduce your bug. I will have a look myself but only if I'm able to reproduce it. Developers are quite often bugged by poor bug reports (this is not the case of this particular bug) and the more information/assets and support you give them to reproduce your problem the more likely they are to actually giving it a look and (hopefully) fix the problem.

**Comment by nsw27** [comment] 2020-06-28 07:28
can try almost any PAK and you should be able to replicate this, anything with big aspect ratio. I've given video examples and extensive details and if anyone is interested in looking into it they know I can provide multiple games and PAKs as examples to test.

Again.. this should not have been prematurely closed, its only a matter of time before other people come across this issue and then its wasted time that could have already addressed the issues....

**Comment by DCurrent** [comment] 2020-06-28 14:02
Tested again on original BOR - does not reproduce. This has developed into a procedural opinion thread - that is not what bug reports are for. I will continue to revisit issue as development continues, but thread is locked until further notice.
