### ISSUE TITLE
Two known crashes from old to new versions and how to solve them

### ISSUE THREAD

**Issue by Toranks** [DCurrent/openbor#189] opened 2020-02-16 18:49 UTC
Adapting a game to a more current version of Openbor I have found two errors that cause crashes without log on new versions (6XXX or 4.0a), but NOT on old ones(4XXX), so it is impossible to find out the origin if you do not know where to look:

- 'atchain 0 0...' causes crashes when pressing the attack button. It is solved by deleting it, as it is unnecessary

- If a "followx" animation calls itself with followanim x (useful for infinite combos), game crashes. The solution is to duplicate the animation (follow1/followanim 2 and follow2/followanim 1 for example), and that one calls the other successively.

**Comment by DCurrent** [comment] 2020-12-03 17:54
Tested both bugs under multiple conditions. They do no reproduce as of revision https://github.com/DCurrent/openbor/commit/36c3aebd5b9726e751315bb8c88c050999a8920e. Atachain 0 disables use of attack as intended. Follows can self chain and do not cause crash. Closing ticket.

**Closed by DCurrent** 2020-12-03 17:54 UTC
