### ISSUE TITLE
Lockup on PSP & Android

### ISSUE THREAD

**Issue by DCurrent** [DCurrent/openbor#27] opened 2018-02-19 15:33 UTC
Android and PSP ports are unstable as of 0eeff9e. Last known good b0e8315.

Per @dbaldan: 

> On the build 4453, the default colourdepth had changed to 32bits, dropping the support to 8 and 16buts. That build has no Android port, so the next available Android support is 4574.
> 
> When you run a mod in Android from that build and on, if you turn of the screen and turn it on back (pausing or not), you face the following:
> 
> - The screen gets black
> - App freezes/hangs but doesn’t closes itself
> - No trace at the log
> - App doesn’t responses to any other Android button (back, home)
> - If you try to drag the notification bar down (by swiping down from the top of the screen), once the notification gets over the frost app, it gets freeze too.
> - If you turn off the screen again and try to turn it on back again, you will need to wait a bit or even the power button won’t response.
> - If you ask to kill background processes in Android (which kills openBOR if its not in focus, as it should), it doesn’t kills it. You have to go to settings and force the APP to close.

@whitedragon0000 attempted a correction in f9b4117 by restoring 8 and 16 bit color modes, but this was not an acceptable solution and has been reverted.

**Comment by jbeich** [comment] 2018-02-19 17:46
> Last known good b0e8315fe5dd.

Probably ba1eb4f62cec instead (see #1) if only binary releases were tested.

**Comment by whitedragon0000** [comment] 2018-02-20 08:50
Making some test (I have no time caused by my real work), I noticed that it works when PAL_BYTES is 768 to make palettes for PSP. I report just this..

**Comment by Plombo** [comment] 2018-02-20 18:39
Okay, that's weird and probably points to some larger issue.

**Comment by whitedragon0000** [comment] 2018-02-21 21:55
Ok, I fixed an overflow issue to access in arrays that have a fixed size 768 (24 bit)
Now psp build doesn't crash anymore. 
For Android issue I can't test or work on it.
In psp build the prev image in menu are not displayed for invalid palette (I don't know the psp format). Can you help me please?

**Comment by dbaldan** [comment] 2018-02-21 22:12
@whitedragon0000 I can test it on Android, but I need someone to compile it, since I had no luck in compiling to Android yet.

**Comment by whitedragon0000** [comment] 2018-02-22 02:11
I can compile just at the end of week...
Issue also in wii (preview image in main menu)

**Comment by whitedragon0000** [comment] 2018-02-23 19:11
Some news?

**Comment by dbaldan** [comment] 2018-02-23 19:12
@whitedragon0000 I can test it only at weekend.

**Comment by dbaldan** [comment] 2018-02-24 01:54
@whitedragon0000 I tested the build 4696 on android, the bug persists.

I had no issue with credits or continue.

**Comment by whitedragon0000** [comment] 2018-02-24 04:47
Anyone can compile new libsdl2.so 2.0.7 for Android?

**Comment by DCurrent** [comment] 2018-02-24 12:19
I don't currently have an Android environment and can't until late next week.

**Comment by dbaldan** [comment] 2018-02-24 16:52
@whitedragon0000 I've tested the build 4699, but the lockup still persists.

**Comment by whitedragon0000** [comment] 2018-02-24 20:04
Android doesn't stuck but on pause it self close and reopen

**Comment by dbaldan** [comment] 2018-02-24 20:34
@whitedragon0000 I've tested both cases:
- Without pausing = OpenBOR closes itself (the unlock screen freezes for a second)
- With pausing = Almost as before (black screen, hang, then cose)

The log only says this (I was in the middle of a level, and there is no trace of all the models cached, loaded, etc)

> Total Ram: 4097757184 Bytes
>  Free Ram: 233533440 Bytes
>  Used Ram: 185328640 Bytes
> 
> SDL video Renderer: opengles 
> 
> 1 joystick(s) found!
> SDL video Renderer: opengles 
> 
> 1 joystick(s) found!
> 
> ************ Shutting Down ************
> 
> OpenBOR v3.0 Build , Compile Date: Feb 24 2018
> Presented by the OpenBOR Team.
> www.chronocrash.com
> OpenBOR is the open source continuation of Beats of Rage by Senile Team.
> 
> Special thanks to SEGA and SNK.
> 
> Total Ram: 4097757184 Bytes
>  Free Ram: 280043520 Bytes
>  Used Ram: 192734208 Bytes
> 
> Release level data...........
> Done!
> 
> Release graphics data........	Done!
> Release game data............
> 
> 
> Release game data............	Done!
> Release timer................	Done!
> Release input hardware.......	Done!
> Release sound system.........	Done!
> Release FileCaching System...	Done!
> 
> **************** Done *****************
> 
> OpenBOR v3.0 Build , Compile Date: Feb 24 2018
> Presented by the OpenBOR Team.
> www.chronocrash.com
> OpenBOR is the open source continuation of Beats of Rage by Senile Team.
> 
> Special thanks to SEGA and SNK.

With pause, now we have a lot, but seams to be the same of the case above

> Total Ram: 4097757184 Bytes
>  Free Ram: 234942464 Bytes
>  Used Ram: 185328640 Bytes
> 
> SDL video Renderer: opengles 
> 
> 1 joystick(s) found!
> SDL video Renderer: opengles 
> 
> 1 joystick(s) found!
> 
> ************ Shutting Down ************
> 
> OpenBOR v3.0 Build , Compile Date: Feb 24 2018
> Presented by the OpenBOR Team.
> www.chronocrash.com
> OpenBOR is the open source continuation of Beats of Rage by Senile Team.
> 
> Special thanks to SEGA and SNK.
> 
> Total Ram: 4097757184 Bytes
>  Free Ram: 268890112 Bytes
>  Used Ram: 192734208 Bytes
> 
> Release level data...........
> Done!
> 
> Release graphics data........	Done!
> Release game data............
> 
> 
> Release game data............	Done!
> Release timer................	Done!
> Release input hardware.......	Done!
> Release sound system.........	Done!
> Release FileCaching System...	Done!
> 
> **************** Done *****************
> 
> OpenBOR v3.0 Build , Compile Date: Feb 24 2018
> Presented by the OpenBOR Team.
> www.chronocrash.com
> OpenBOR is the open source continuation of Beats of Rage by Senile Team.
> 
> Special thanks to SEGA and SNK.

**Comment by whitedragon0000** [comment] 2018-02-25 03:20
for android I have improved the SDLActivity and fixed the use of wakelock,
Now we need to compile new SDL2 2.0.7 with #define SDL_ANDROID_BLOCK_ON_PAUSE  1
Anyone? I can't... (I've windows). We need new libsdl2.so (2.0.7)

**Comment by whitedragon0000** [comment] 2018-02-25 16:18
It's strange that log.
BEFORE ************ Shutting Down ************
We expeted a MSG first. Why No msg? We need to figure out what exception fires this shutdown();
I need help because for this week I cant work to openbor.
I hope in DC and Plombo...

**Comment by DCurrent** [comment] 2018-02-25 16:32
As above, I don't have Android environment to compile and can't do anything this conning week. After that I can compile and Android build and do some testing.

**Comment by whitedragon0000** [comment] 2018-02-25 16:34
thanks...

**Comment by whitedragon0000** [comment] 2018-02-25 16:45
ah... may is a shutdown(0,...) (my investigate without test, just looking the code...)
cases are 2: quit in openbor.c or SDL_QUIT in sdl/control.c
My look is on sdl/control.c... from while(SDL_PollEvent(&ev))...
Maybe need do add some control in switch case SDL_QUIT to check the home button...

**Comment by whitedragon0000** [comment] 2018-02-25 16:57
Here... I think that in switch... case SDL_QUIT we need to add the pause check.
Example:
#ifdef ANDROID
			case SDL_APP_TERMINATING:
				shutdown(0, DEFAULT_SHUTDOWN_MESSAGE);
				break;
#else
			case SDL_QUIT:
				shutdown(0, DEFAULT_SHUTDOWN_MESSAGE);
				break;
#endif

This is a possibile patch...

**Comment by whitedragon0000** [comment] 2018-02-25 17:17
or... SDL_QUIT ievent is called by SDLActivity.nativeQuit(); fro java code...
So we need to figure why the onDestroy event fires...

**Comment by crxtrdude** [comment] 2018-02-26 10:21
> Anyone can compile new libsdl2.so 2.0.7 for Android?

To answer that, the last known version that can run libsdl2 on 
Android 2.2 is 2.0.4. That was the version I had compiled for OpenBOR.

If you guys want to make an libsdl2 with the latest build, you guys could do it with yourselves. I had the old projects here for compiling sdl2, but unfortunately I couldn't compile because I reformatted my comp to 64 bit.

**Comment by crxtrdude** [comment] 2018-02-26 10:30
[CompileFiles.zip](https://github.com/DCurrent/openbor/files/1758140/CompileFiles.zip)

Here's the Android.mk I used for SDL2. You could tweak appropriately for the latest SDL. Compiling is similar to OpenBOR with a build.bat. As long as you tweak properly the files in android-project folder

**Comment by whitedragon0000** [comment] 2018-02-26 20:25
Hi crxtrdude! can you help us to fix the issue?

**Comment by whitedragon0000** [comment] 2018-02-28 11:32
Read here: [](https://forums.libsdl.org/viewtopic.php?p=50122)
You can read that the sdl 2.0.4 suffers that issue..
I can compile (I use win64)...
Anyone can compile latest build (2.0.7)?

**Comment by DCurrent** [comment] 2018-02-28 11:51
I agree with you @whitedragon0000 but would like to get a community consensus before we effectively end support for older Androids. I'll make a post when I get to work  or you can if you like.

**Comment by crxtrdude** [comment] 2018-02-28 12:15
Yeah, some people might have older devices. A compromise would be we post the last working android build and note that it's not supported by the devs and only use case for it is for older games, while the newer ones with the newer SDL would be the one supported by us or something like that. But again, it depends on the community whether or not they would do so.

My english today's a bit sketchy sorry bout that.

**Comment by crxtrdude** [comment] 2018-02-28 12:50
By the way, I'm downloading the tools required to compile to Android NDK, maybe I could give some help if I can, but it's not a guarantee.

**Comment by dbaldan** [comment] 2018-02-28 13:24
@DCurrent @whitedragon0000 Can I give my opinion?
If this update, which will won't support old devices anymore (how old are we talking about?) its the **only way** to fix the Android port - which it's _not functional_ for now - then we have no other option.

But if there is another way, yeah, I think we should look for another solution.

**Comment by DCurrent** [comment] 2018-02-28 14:12
@dbaldan that's my way of thinking too, I'd just like to get community word on it. I don't have to ask permission to do anything, but I think it only fair to let others weigh in. I also agree that exactly what devices are affected is a big question. By their nature, mobile devices more or less have to be updated in order to continue using them for their intended purpose. It's one thing if we are going to break devices just one generation back - that would be unacceptable. But we're not going to cater to people like... well, me... who keep defunct androids around to just use as camera boxes and such.

**Comment by whitedragon0000** [comment] 2018-03-03 15:50
I think this is the one solution.: out 2.0.8!

**Comment by dbaldan** [comment] 2018-03-17 03:28
WhiteDragon, I've tested the latest version (4742):

If you turn off the screen and turn it back again, the screen gets black but instead of crashing, OpenBor will just reset.

After some time, the engine just close itself.

Here is the log :

Total Ram: 4097286144 Bytes
 Free Ram: 228663296 Bytes
 Used Ram: 189664768 Bytes

SDL video Renderer: opengles2 

1 joystick(s) found!
SDL video Renderer: opengles2 

1 joystick(s) found!

************ Shutting Down ************

OpenBOR v3.0 Build , Compile Date: Mar 17 2018
Presented by the OpenBOR Team.
www.chronocrash.com
OpenBOR is the open source continuation of Beats of Rage by Senile Team.

Special thanks to SEGA and SNK.

Total Ram: 4097286144 Bytes
 Free Ram: 288722944 Bytes
 Used Ram: 194193920 Bytes

Release level data...........
Done!

Release graphics data........	Done!
Release game data............


Release game data............	Done!
Release timer................	Done!
Release input hardware.......	Done!
Release sound system.........	Done!
Release FileCaching System...	Done!

**************** Done *****************

OpenBOR v3.0 Build , Compile Date: Mar 17 2018
Presented by the OpenBOR Team.
www.chronocrash.com
OpenBOR is the open source continuation of Beats of Rage by Senile Team.

Special thanks to SEGA and SNK.

--------

**Comment by whitedragon0000** [comment] 2018-03-17 14:26
Yes I know, latest issue is shutdown on power button. Home button is OK instead. 
I checked and when you use power button the pollevent fires SDL_QUIT into control.c.
I don't know why... I hope in some. Help..

**Comment by whitedragon0000** [comment] 2018-03-17 14:57
Yes I know, latest issue is shutdown on power button. Home button is OK instead. 
I checked and when you use power button the pollevent fires SDL_QUIT into control.c.
I don't know why... I hope in some. Help..

**Comment by dbaldan** [comment] 2018-03-17 14:58
Yes, HOME BUTTON is okay now.

**Comment by whitedragon0000** [comment] 2018-03-18 17:02
Update code. 
You can read here: https://developer.android.com/guide/topics/resources/runtime-changes.html
Maybe issue is on manifest. onDestroy() event is fired by Power button when manifest is not correctly configured. From API 13 to up need to configure or add to android:configChanges the screenSize (screenLayout?????) and add the check event onConfigurationChanged() in activity.
Now I can't compile... Can you check form me?

**Comment by whitedragon0000** [comment] 2018-03-24 03:01
All solved by me!!

**Comment by crxtrdude** [comment] 2018-03-24 03:04
You're still using API 13 for this fix?

**Comment by dbaldan** [comment] 2018-03-24 04:38
Have you compiled the android version? I would like to test.

**Comment by whitedragon0000** [comment] 2018-03-28 21:22
Issue on touch on virtual game pad

**Closed** 2018-04-01 23:50 UTC
Labels: bug, help wanted
