### ISSUE TITLE
panel alignment

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#161] opened 2019-06-14 21:10 UTC
there was a issue I saw with latest engine build for PC regarding aligning of panels

![empty - 0001](https://user-images.githubusercontent.com/45753033/59485045-9024c900-8eb7-11e9-888b-f8635cb4eecb.png)

normally the black bar fills screen properly. here is the code

`name	filter

type	panel
speed 10
noquake 1 1
facing 1
setlayer 999
subject_to_screen 1

offscreenkill 9999

palette none

anim	idle
	loop	0
	delay	5
	offset	0 0
	bbox	0 0 0 0
frame	data/bgs/streets/filterc.png
frame	data/bgs/streets/filterb.png
	frame	data/bgs/streets/filter.png`

here is a sprite from panel

![filter](https://user-images.githubusercontent.com/45753033/59538966-d709d180-8f3e-11e9-8bbf-fafa23f93afc.png)

video aspect ratio is video 960x480 for 2 games I tested with same panel issues for different panels

I just tested another game of mine with aspect ratio video 1060x580 and didn't seem to see a issue with similar panels

could be wrong but in engine compile I see there is something called fixindentation.sh that sounds like there was indentation issue before ?

ALSO seems panels that should be subject to screen aren't and will move when player moves and screen/level scrolls (well they stay in spawned position instead of being where they should be to appear to remain as per screen) I feel this may be related... but can make a separate issue post if needed ?

**Comment by DCurrent** [comment] 2019-06-14 21:21
Please attach the panel sprites, that will help with reproduction and diagnosis.

**Comment by nsw27** [comment] 2019-06-14 21:27
have updated first post

**Comment by nsw27** [comment] 2019-06-29 22:20
has anyone investigated ? is there any further information i can provide ?

**Comment by nsw27** [comment] 2019-08-03 22:06
any updates on this matter ?

**Comment by DCurrent** [comment] 2019-12-09 16:47
Just put this one through the test gauntlet. Could not reproduce any alignment issue at all. See screenshot with black box example sprite. Furthermore, the already existing background is also comprised of animated panels - 8 layers of them to be exact: Four layers of water, palm leaves in foreground (obscured by the black box), docks with lighting, and two layers of boats. This stage has existed with no updates since 2010 and does not exhibit any alignment problems running latest alpha build, nor any conflicts with addition of black box example panel. Closing. 

![bor - 0032](https://user-images.githubusercontent.com/5900142/70454450-70dab300-1a78-11ea-8b9b-846d59da7c1c.png)

**Closed by DCurrent** 2019-12-09 16:47 UTC
