### ISSUE TITLE
Wii port - Various errors in some pak games

### ISSUE THREAD

**Issue by SieKensou** [DCurrent/openbor#72] opened 2018-08-10 16:15 UTC
As you will noticed I'm testing OpenBOR on the Wii this days. I know some of the issues can be caused for bad programming in the pak files themselves but I will tell you the problems I have found in different games for possible fixes.

1-Art of Fighting - Beats Of Rage Remix III:
All bugs was fixed in a updated versión, so they were bugs of the module.

2-Night Slashers X:
Fixed by msmalik681 and White Dragon.

3-Fighters History Revenge:
Fixed, it was problem with the frequency of the sounds.

4-Streets Of Rage 2X:
When it's loading the title screen it goes back to the homebrew channel... (Out of memory error!). I don't know if this can be fixed making the games loading what they need only (I noticed it loads all the stages, characters, enemies..... etc at the beginning and in big games this breaks the limits of the Wii). This is a good game and it would be great to have a way to play it on the Wii.

5-Golden Axe Revenge:
When you ride a dragon and you are in certain zones (in the first stage when you jump over the first platform) the fireball of the dragon is not fired (although it shows its animation).
I checked some videos and it should works well.

6-Preview screenshots are not showed on the game select menú.

And I'm not sure if this is in all version or just the Wii port, but I always have to put the SFX volume at max because the sound effects sounds very low...

**Comment by DCurrent** [comment] 2018-08-10 17:54
If I may, a lot of these tests would be more helpful if you conducted them on the PC version under same conditions. This would go a long way toward helping us discern what the issue is.

- Wii port bug
- Engine Bug
- Backward compatibility issue (we try to keep full backward compatibility, but things happen)
- Author error in the module.

Thanks for ally our help!

**Comment by msmalik681** [comment] 2018-08-10 18:29
Most of these issues are the mods not being optimised for Wii some mods are just too heavy to run but some mods can run with a simple fix just extract the mod then compress all sound effect files to the lowest setting 8-bit mono 6000Hz this will fix any garbage sound effects and reduce the memory consumed (the Wii only has 64mb ram).

I am trying now to fix the issue with being thrown to the right it is a bit of a pain but I am working with the higher developers to resolve this issue. (I think this is the only real bug).

You forgot to mention the preview issue with the wii lol.

**Comment by SieKensou** [comment] 2018-08-10 22:12
Thanks to all for the replies. 

@dbaldan
I'm editing the sound files of the Fighters History Revenge to see if it works (it's a mess, some are in stereo, some in mono, some in 16 bits, some in 8 bits....). It will take a while because there are too much sound effects and I don't have too much time, but it's good to see it can work fine after that. (anyone can tell me how to make the pak again? I extracted it but then using the data folder on the packer.bat doesn't work...).
About the Streets of Rage 2X is a pity I can't play it on the Wii, I hope the Power Rangers Beats of Power works fine but seeing it's too big in size it probabbly won't work either :(
I'm really interested in this engine for the Wii and it would be great to have it as optimized and fixed as possible :D

@DCurrent
I prefer to play this games on the Wii and I'm not interested in playing them on PC, but I will test when neccessary to make some tests. The bugs I said here only happens on the Wii version (except the palette bug in character select screen of Art of Fighting Beats of Rage Remix III that I saw it in a video too. I checked the gif images of the character select screen and that 3 are wrong (anyone here knows how to fix these images? they should have the same palette than the character).

@msmalik681
Yeah, I understant that not all people thinks on the Wii when they make this games, but thanks for let me know about that way to save space in some games.
Thanks for your effort in triying to fix that bug, I really hope you can find a way to solve it.
I didn't mentioned the preview issue because I still didn't knew it was an issue lol
I was thinking it was me not knowing how/where to put the screenshots....

**Comment by SieKensou** [comment] 2018-08-10 22:38
@dbaldan 
Yes, I'm using GoldWave, but I was doing it one by one to fix the files that has some noises at the end or something. Thanks for the tip, I didn't noticed that Batch Processing option :)
Do you know how to change the Hz of the wav files? When I save the file I just can change to wav 8 bits mono or stereo but I don't see the Hz option and some of the sounds are in 44100Hz. In the mp3 I can save in different Hz but I don't see that option for wav.
Do you know how I have to do to make the .pak fila again? I have the packer.bat file with the OpenBOR.exe and the borpak.exe. I tried to put the data folder over the bat but didn't worked…
Thanks in advance.

**Comment by dbaldan** [comment] 2018-08-10 22:44
@SieKensou they had changed this over time, but I am not wrong, when you go and save, there is a button where you can choose the frequency (or you can go and use RESAMPLE). I can't confirm it right now because I am on a Mac, but I am pretty sure there is an option for resample (but it will ask you the frenquency when you save).

You need borpak.exe

Save this as a .bat and run it:
borpak.exe -d DATA -b YOURGAME.pak

**Comment by SieKensou** [comment] 2018-08-12 09:45
Thanks @dbaldan it worked fine and now I can resample the sound effects and compile the pak. I updated the first post. The Art of Fighting Beats of Rage Remix III bugs was bugs in the module that were fixed later. The Fighters History Revenge problem is what you said, so resampling all the sound effects fix the problem (good to know because I found the same problem in more games I have tested).

@msmalik681 
The sound effects plays to low, I always have to put the SFX volumen at max and even with that it doesn't sound very high…. is there any problem that causes this?

Thanks for all the good job!

**Comment by msmalik681** [comment] 2018-08-12 09:58
The engine should have settings for sound effects try deleting your saves folder and then re-run the game.

With the below link you will find a test build please check Nightslashers X and see if you can perform the moves when facing left now.

http://www.chronocrash.com/forum/index.php?topic=3990.msg55419#msg55419

**Comment by SieKensou** [comment] 2018-08-12 15:03
Okay, I will try deleting all the config.

I tested that latest build you said with Night Slashers X and sadly the problem is still there :(

**Comment by msmalik681** [comment] 2018-08-13 20:25
I will try to fix the issue with the previews next.

**Comment by DCurrent** [comment] 2018-08-13 21:05
Guys, please limit each issue request thread to a single bug. This lets us keep a better workflow to track the issues and close them out.

**Comment by SieKensou** [comment] 2018-08-15 21:30
Okay DCurrent, sorry. For the next time I won't put various bugs in the same issue.
Thanks for the good job you all are doing with this great engine.

**Comment by msmalik681** [comment] 2018-08-20 22:02
As you have started a new issue for the SFX I will close this as everything else has been resolved.

**Closed by msmalik681** 2018-08-20 22:02 UTC
